name: Deploy to Lightsail

env:
  DEPLOY_PACKAGE_NAME_FILE: "${{ github.sha }}.zip"
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone https://github.com/Ravi1491/currency-convertor
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME_FILE }} ./dist/ -x *.git*

      - name: Copy file via SSH password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          source: ${{ env.DEPLOY_PACKAGE_NAME_FILE }}
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}"

      - name: Connect to AWS Lightsail, extract file, and start production server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            sudo apt-get update && sudo apt-get install -y unzip
            unzip -q -o "/home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }}" -d "/home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ secrets.LIGHTSAIL_ROOT_DIR }}"
            rm "/home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }}"
            cd "/home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ secrets.LIGHTSAIL_ROOT_DIR }}/dist"
            npx http-server -p 3000 -d false
