name: Deploy to Lightsail

env:
  DEPLOY_PACKAGE_NAME_FILE: "${{ github.sha }}.zip"
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"
  LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone https://github.com/Ravi1491/currency-convertor
        uses: actions/checkout@v2

      - name: Install Our App
        run: npm install && npm run build

      - name: Check environment variables
        run: env

      - name: This create an env file incase we need one.
        run: |
          echo LIGHTSAIL_USERNAME= ${{ secrets.LIGHTSAIL_USERNAME }}

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME_FILE }} ./dist/ -x *.git*

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          source: ${{ env.DEPLOY_PACKAGE_NAME_FILE }}
          target: "/home/${{ secrets.LIGHTSAIL_USERNAME }}"

      - name: Connect to AWS Lightsail, extract file and delete the file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_KEY }}
          password: ""
          passphrase: ""
          port: 22
          script: |
            sudo apt-get install zip unzip
            unzip -q -o /home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }} -d /home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ secrets.LIGHTSAIL_ROOT_DIR }}
            rm /home/${{ secrets.LIGHTSAIL_USERNAME }}/${{ env.DEPLOY_PACKAGE_NAME_FILE }}
            sudo systemctl restart nginx
      - name: Deployment completed Successfully
        run: echo "Deployment completed successfuly"
